import io, os, re
p = r"C:\bots\ecosys\agents\brain_agent.py"
s = open(p, "r", encoding="utf-8", errors="ignore").read()
anchor = "    # --------- UPDATED: Run method adds retry handler and uses bus.on ----------\n"
i = s.find(anchor)
if i == -1:
    # fallback to async def run signature
    m = re.search(r"\n\s{4}async def run\(self\)\s*->\s*None\s*:\s*\n", s)
    if not m:
        raise SystemExit("run() anchor not found")
    i = m.start() + 1
new_block = (
    "    # --------- UPDATED: Run method adds retry handler and uses bus.on ----------\n"
    "    async def run(self) -> None:\n"
    "        try:\n"
    "            on = getattr(self.bus, \"on\", None)\n"
    "            if not callable(on):\n"
    "                return\n\n"
    "            async def _on_new(msg: Any) -> None:\n"
    "                try:\n"
    "                    job_id = getattr(msg, \"job_id\", None) or (msg.get(\"job_id\") if isinstance(msg, dict) else None)\n"
    "                    self._reset_budget(job_id)\n"
    "                    await self.plan(msg)\n"
    "                except Exception:\n"
    "                    pass\n\n"
    "            async def _on_retry(msg: Any) -> None:\n"
    "                try:\n"
    "                    job_id = getattr(msg, \"job_id\", None) or (msg.get(\"job_id\") if isinstance(msg, dict) else None)\n"
    "                    if not self._inc_and_check_budget(job_id):\n"
    "                        try:\n"
    "                            await self.bus.publish(\"task/budget_exhausted\", {\"job_id\": job_id}, sender=self.name, job_id=job_id)\n"
    "                        except Exception:\n"
    "                            pass\n"
    "                        try:\n"
    "                            await self.bus.publish(\"ui/print\", {\"text\": f\"{self.name}: retry budget exhausted for job {job_id}\"}, sender=self.name, job_id=job_id)\n"
    "                        except Exception:\n"
    "                            pass\n"
    "                        return\n\n"
    "                    plan = None\n"
    "                    feedback = None\n"
    "                    if isinstance(msg, dict):\n"
    "                        data = msg.get(\"data\") or {}\n"
    "                        plan = data.get(\"plan\")\n"
    "                        feedback = data.get(\"feedback\")\n"
    "                    if feedback:\n"
    "                        await self.bus.publish(\"ui/print\", {\"text\": f\"{self.name}: (Autofix) {feedback}\"}, sender=self.name, job_id=job_id)\n"
    "                    if plan:\n"
    "                        try:\n"
    "                            jid = str(job_id or \"\")\n"
    "                            if jid:\n"
    "                                self._job_plans[jid] = plan\n"
    "                        except Exception:\n"
    "                            pass\n"
    "                        await self.bus.publish(\"task/plan\", plan, sender=self.name, job_id=job_id)\n"
    "                        await self.bus.publish(\"task/exec\", {\"plan\": plan, \"steps\": plan.get(\"steps\", [])}, sender=self.name, job_id=job_id)\n"
    "                    else:\n"
    "                        await self.plan(msg)\n"
    "                except Exception:\n"
    "                    pass\n\n"
    "            async def _on_task_result(msg: Any) -> None:\n"
    "                try:\n"
    "                    job_id = getattr(msg, \"job_id\", None) or (msg.get(\"job_id\") if isinstance(msg, dict) else None)\n"
    "                    data = (msg.get(\"data\") if isinstance(msg, dict) else {}) or {}\n"
    "                    txt = str(data.get(\"text\") or \"\")\n"
    "                    if job_id:\n"
    "                        self._job_texts.setdefault(str(job_id), []).append(txt)\n"
    "                except Exception:\n"
    "                    pass\n\n"
    "            async def _on_worker_done(msg: Any) -> None:\n"
    "                try:\n"
    "                    job_id = getattr(msg, \"job_id\", None) or (msg.get(\"job_id\") if isinstance(msg, dict) else None)\n"
    "                    jid = str(job_id or \"\")\n"
    "                    data = (msg.get(\"data\") if isinstance(msg, dict) else {}) or {}\n"
    "                    plan = None\n"
    "                    if isinstance(data, dict):\n"
    "                        plan = data.get(\"plan\")\n"
    "                    collected = list(self._job_texts.get(jid, []))\n"
    "                    success = []\n"
    "                    if isinstance(plan, dict):\n"
    "                        success = list(plan.get(\"success\") or [])\n"
    "                    if not plan and jid in self._job_plans:\n"
    "                        plan = self._job_plans.get(jid)\n"
    "                        if isinstance(plan, dict):\n"
    "                            success = list(plan.get(\"success\") or [])\n"
    "                    evaluation = evaluate_success_from_texts(success, collected)\n"
    "                    if evaluation.get(\"ok\"):\n"
    "                        try:\n"
    "                            await self.bus.publish(\"ui/print\", {\"text\": f\"{self.name}: Job {jid} success.\"}, sender=self.name, job_id=job_id)\n"
    "                        except Exception:\n"
    "                            pass\n"
    "                        try:\n"
    "                            if jid in self._job_texts:\n"
    "                                del self._job_texts[jid]\n"
    "                        except Exception:\n"
    "                            pass\n"
    "                        return\n"
    "                    base_plan = plan or self._job_plans.get(jid) or {}\n"
    "                    plan2 = replan_if_needed(base_plan, evaluation)\n"
    "                    try:\n"
    "                        if jid:\n"
    "                            self._job_plans[jid] = plan2\n"
    "                    except Exception:\n"
    "                        pass\n"
    "                    await self.bus.publish(\"task/retry\", {\"plan\": plan2, \"feedback\": \"evaluation failed\"}, sender=self.name, job_id=job_id)\n"
    "                except Exception:\n"
    "                    pass\n\n"
    "            r1 = on(\"task/new\", _on_new)\n"
    "            r2 = on(\"task/retry\", _on_retry)\n"
    "            r3 = on(\"task/result\", _on_task_result)\n"
    "            r4 = on(\"worker/done\", _on_worker_done)\n\n"
    "            if inspect.isawaitable(r1):\n"
    "                await r1\n"
    "            if inspect.isawaitable(r2):\n"
    "                await r2\n"
    "            if inspect.isawaitable(r3):\n"
    "                await r3\n"
    "            if inspect.isawaitable(r4):\n"
    "                await r4\n"
    "        except Exception:\n"
    "            return\n"
)
# replace from anchor to end of file with new_block
ns = s[:i] + new_block
open(p, "w", encoding="utf-8", errors="ignore").write(ns)
print("patched")
