# sample_calc_cli.py (generated by ToolForge)
import sys, json, importlib
def main():
    mod = importlib.import_module("tools.sample_calc.sample_calc")
    fn  = getattr(mod, "main", None)
    res = fn() if callable(fn) else {"ok": False, "error": "entry not callable"}
    print(json.dumps(res))
if __name__ == "__main__": main()
